package view.actions;

import java.util.List;

import view.components.ImageProcessingMenuBar;

/**
 * A semantic event which indicates that a component-defined action occurred. This high-level
 * event is generated by a component, such as {@link ImageProcessingMenuBar}
 * when a menu item is clicked/activated.
 *
 * <p>The class offers methods to fetch a string representing the action command. It also
 * encapsulates metadata pertaining to the event in a list of strings. The nature of the
 * contents of the list depends on the component emitting the action event and the nature of the
 * action command.
 * </p>
 */
public class Action {
  private String actionCommand;
  private List<String> metadata;

  /**
   * Instantiates a new action object with the provided action command and metadata.
   *
   * @param actionCommand action command.
   * @param metadata string list containing metadata pertaining to the action.
   */
  public Action(String actionCommand, List<String> metadata) {
    this.actionCommand = actionCommand;
    this.metadata = metadata;
  }

  /**
   * Returns the action command pertaining to the action.
   *
   * @return action command.
   */
  public String getActionCommand() {
    return actionCommand;
  }

  /**
   * Returns the metadata pertaining to the action.
   *
   * @return action metadata.
   */
  public List<String> getMetadata() {
    return this.metadata;
  }
}
